export const sample_foods = [
  {
    id: 1,
    name: "Margherita Pizza",
    cookTime: 20,
    price: 12.99,
    favorite: true,
    origins: ["Italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["Pizza", "italian", "Dinner"],
  },
  {
    id: 2,
    name: "Chicken Alfredo Pasta",
    cookTime: 30,
    price: 15.99,
    favorite: false,
    origins: ["Italy"],
    stars: 4.2,
    imageUrl: "food-2.jpg",
    tags: ["Pasta", "italian", "Dinner"],
  },
  {
    id: 3,
    name: "Vegetarian Stir-Fry",
    cookTime: 25,
    price: 10.99,
    favorite: true,
    origins: ["Asia"],
    stars: 4.8,
    imageUrl: "food-3.jpg",
    tags: ["vegetarian", "asian", "Lunch"],
  },
  {
    id: 4,
    name: "Classic Hamburger",
    cookTime: 15,
    price: 8.99,
    favorite: false,
    origins: ["USA"],
    stars: 4.0,
    imageUrl: "food-4.jpg",
    tags: ["FastFood", "Lunch", "Hamburger"],
  },
  {
    id: 5,
    name: "Sushi Platter",
    cookTime: 40,
    price: 24.99,
    favorite: true,
    origins: ["Japan"],
    stars: 4.7,
    imageUrl: "food-5.jpg",
    tags: ["sushi", "japanese", "Dinner"],
  },
  {
    id: 6,
    name: "Mango Sticky Rice",
    cookTime: 15,
    price: 7.99,
    favorite: false,
    origins: ["Thailand"],
    stars: 4.3,
    imageUrl: "food-6.jpg",
    tags: ["Dessert", "thai", "snack"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "Hamburger", count: 1 },
  { name: "Dessert", count: 1 },
  { name: "Dinner", count: 3 },
  { name: "Pasta", count: 1 },
];
